# Generated by Django 4.0.4 on 2022-05-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('profile_id', models.IntegerField(verbose_name='Идентификатор профиля')),
                ('blogpost_id', models.IntegerField(verbose_name='Идентификатор поста блога')),
                ('is_read', models.BooleanField(verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Пост ленты',
                'verbose_name_plural': 'Посты ленты',
            },
        ),
    ]
