# Generated by Django 4.0.4 on 2022-05-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_blogpost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostReadMark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('profile_id', models.IntegerField(verbose_name='Идентификатор профиля')),
                ('blogpost_id', models.IntegerField(verbose_name='Идентификатор поста блога')),
            ],
            options={
                'verbose_name': 'Метка "прочитано"',
                'verbose_name_plural': 'Метки "прочитано"',
            },
        ),
    ]
